[2022-11-16 01:34:44,568] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: hello_world.goodbye_task 2022-03-09T00:00:00+00:00 [queued]>
[2022-11-16 01:34:45,919] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: hello_world.goodbye_task 2022-03-09T00:00:00+00:00 [queued]>
[2022-11-16 01:34:46,228] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2022-11-16 01:34:46,261] {taskinstance.py:1043} INFO - Starting attempt 1 of 1
[2022-11-16 01:34:46,274] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2022-11-16 01:34:47,657] {taskinstance.py:1063} INFO - Executing <Task(PythonOperator): goodbye_task> on 2022-03-09T00:00:00+00:00
[2022-11-16 01:34:48,013] {standard_task_runner.py:52} INFO - Started process 439 to run task
[2022-11-16 01:34:48,403] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'hello_world', 'goodbye_task', '2022-03-09T00:00:00+00:00', '--job-id', '89', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/index.py', '--cfg-path', '/tmp/tmph7gnoiuj', '--error-file', '/tmp/tmp2bnxtytu']
[2022-11-16 01:34:48,431] {standard_task_runner.py:77} INFO - Job 89: Subtask goodbye_task
[2022-11-16 01:34:54,288] {logging_mixin.py:104} INFO - Running <TaskInstance: hello_world.goodbye_task 2022-03-09T00:00:00+00:00 [running]> on host 001906ffd7c9
[2022-11-16 01:34:59,721] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=hello_world
AIRFLOW_CTX_TASK_ID=goodbye_task
AIRFLOW_CTX_EXECUTION_DATE=2022-03-09T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-03-09T00:00:00+00:00
[2022-11-16 01:34:59,846] {logging_mixin.py:104} INFO - bye all
[2022-11-16 01:34:59,864] {python.py:118} INFO - Done. Returned value was: bye
[2022-11-16 01:35:03,210] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=hello_world, task_id=goodbye_task, execution_date=20220309T000000, start_date=20221116T013444, end_date=20221116T013503
[2022-11-16 01:35:08,419] {taskinstance.py:1220} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-11-16 01:35:08,856] {local_task_job.py:188} WARNING - State of this instance has been externally set to success. Terminating instance.
[2022-11-16 01:35:09,026] {process_utils.py:100} INFO - Sending Signals.SIGTERM to GPID 439
[2022-11-16 01:35:09,612] {process_utils.py:66} INFO - Process psutil.Process(pid=439, status='terminated', exitcode=0, started='01:34:47') (439) terminated with exit code 0
