[2022-11-16 01:29:48,813] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: hello_world.hello_task 2022-02-14T00:00:00+00:00 [queued]>
[2022-11-16 01:29:54,112] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: hello_world.hello_task 2022-02-14T00:00:00+00:00 [queued]>
[2022-11-16 01:29:54,160] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2022-11-16 01:29:54,177] {taskinstance.py:1043} INFO - Starting attempt 1 of 1
[2022-11-16 01:29:54,203] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2022-11-16 01:29:56,657] {taskinstance.py:1063} INFO - Executing <Task(PythonOperator): hello_task> on 2022-02-14T00:00:00+00:00
[2022-11-16 01:29:58,351] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'hello_world', 'hello_task', '2022-02-14T00:00:00+00:00', '--job-id', '46', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/index.py', '--cfg-path', '/tmp/tmp9mpk1zqi', '--error-file', '/tmp/tmp0matjejd']
[2022-11-16 01:29:58,393] {standard_task_runner.py:77} INFO - Job 46: Subtask hello_task
[2022-11-16 01:29:57,692] {standard_task_runner.py:52} INFO - Started process 273 to run task
[2022-11-16 01:30:01,613] {logging_mixin.py:104} INFO - Running <TaskInstance: hello_world.hello_task 2022-02-14T00:00:00+00:00 [running]> on host 001906ffd7c9
[2022-11-16 01:30:07,069] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=hello_world
AIRFLOW_CTX_TASK_ID=hello_task
AIRFLOW_CTX_EXECUTION_DATE=2022-02-14T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-02-14T00:00:00+00:00
[2022-11-16 01:30:07,139] {logging_mixin.py:104} INFO - hi everyone
[2022-11-16 01:30:07,173] {python.py:118} INFO - Done. Returned value was: hello world
[2022-11-16 01:30:11,823] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=hello_world, task_id=hello_task, execution_date=20220214T000000, start_date=20221116T012949, end_date=20221116T013011
[2022-11-16 01:30:17,097] {local_task_job.py:188} WARNING - State of this instance has been externally set to success. Terminating instance.
[2022-11-16 01:30:18,273] {process_utils.py:100} INFO - Sending Signals.SIGTERM to GPID 273
[2022-11-16 01:30:19,588] {taskinstance.py:1239} ERROR - Received SIGTERM. Terminating subprocesses.
[2022-11-16 01:30:21,918] {process_utils.py:66} INFO - Process psutil.Process(pid=273, status='terminated', exitcode=1, started='01:29:56') (273) terminated with exit code 1
