[2022-11-16 01:26:06,170] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: hello_world.hello_task 2022-01-08T00:00:00+00:00 [queued]>
[2022-11-16 01:26:08,788] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: hello_world.hello_task 2022-01-08T00:00:00+00:00 [queued]>
[2022-11-16 01:26:08,882] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2022-11-16 01:26:08,899] {taskinstance.py:1043} INFO - Starting attempt 1 of 1
[2022-11-16 01:26:08,905] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2022-11-16 01:26:11,172] {taskinstance.py:1063} INFO - Executing <Task(PythonOperator): hello_task> on 2022-01-08T00:00:00+00:00
[2022-11-16 01:26:11,924] {standard_task_runner.py:52} INFO - Started process 133 to run task
[2022-11-16 01:26:13,459] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'hello_world', 'hello_task', '2022-01-08T00:00:00+00:00', '--job-id', '11', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/index.py', '--cfg-path', '/tmp/tmpgwa7koqt', '--error-file', '/tmp/tmpl596315g']
[2022-11-16 01:26:13,678] {standard_task_runner.py:77} INFO - Job 11: Subtask hello_task
[2022-11-16 01:26:24,289] {logging_mixin.py:104} INFO - Running <TaskInstance: hello_world.hello_task 2022-01-08T00:00:00+00:00 [running]> on host 001906ffd7c9
[2022-11-16 01:26:31,904] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=hello_world
AIRFLOW_CTX_TASK_ID=hello_task
AIRFLOW_CTX_EXECUTION_DATE=2022-01-08T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-01-08T00:00:00+00:00
[2022-11-16 01:26:32,494] {logging_mixin.py:104} INFO - hi everyone
[2022-11-16 01:26:32,683] {python.py:118} INFO - Done. Returned value was: hello world
[2022-11-16 01:26:36,622] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=hello_world, task_id=hello_task, execution_date=20220108T000000, start_date=20221116T012606, end_date=20221116T012636
[2022-11-16 01:26:45,789] {local_task_job.py:188} WARNING - State of this instance has been externally set to success. Terminating instance.
[2022-11-16 01:26:45,614] {taskinstance.py:1220} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-11-16 01:26:46,803] {process_utils.py:100} INFO - Sending Signals.SIGTERM to GPID 133
[2022-11-16 01:26:47,402] {process_utils.py:66} INFO - Process psutil.Process(pid=133, status='terminated', exitcode=0, started='01:26:11') (133) terminated with exit code 0
