[2022-11-16 01:26:35,651] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: hello_world.hello_task 2022-01-13T00:00:00+00:00 [queued]>
[2022-11-16 01:26:37,823] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: hello_world.hello_task 2022-01-13T00:00:00+00:00 [queued]>
[2022-11-16 01:26:37,931] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2022-11-16 01:26:37,947] {taskinstance.py:1043} INFO - Starting attempt 1 of 1
[2022-11-16 01:26:37,985] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2022-11-16 01:26:42,807] {taskinstance.py:1063} INFO - Executing <Task(PythonOperator): hello_task> on 2022-01-13T00:00:00+00:00
[2022-11-16 01:26:42,976] {standard_task_runner.py:52} INFO - Started process 145 to run task
[2022-11-16 01:26:44,313] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'hello_world', 'hello_task', '2022-01-13T00:00:00+00:00', '--job-id', '13', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/index.py', '--cfg-path', '/tmp/tmpkpwwzuil', '--error-file', '/tmp/tmpmz0sh3zr']
[2022-11-16 01:26:44,409] {standard_task_runner.py:77} INFO - Job 13: Subtask hello_task
[2022-11-16 01:26:52,265] {logging_mixin.py:104} INFO - Running <TaskInstance: hello_world.hello_task 2022-01-13T00:00:00+00:00 [running]> on host 001906ffd7c9
[2022-11-16 01:26:57,479] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=hello_world
AIRFLOW_CTX_TASK_ID=hello_task
AIRFLOW_CTX_EXECUTION_DATE=2022-01-13T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-01-13T00:00:00+00:00
[2022-11-16 01:26:57,609] {logging_mixin.py:104} INFO - hi everyone
[2022-11-16 01:26:57,628] {python.py:118} INFO - Done. Returned value was: hello world
[2022-11-16 01:26:59,200] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=hello_world, task_id=hello_task, execution_date=20220113T000000, start_date=20221116T012635, end_date=20221116T012659
[2022-11-16 01:27:02,095] {taskinstance.py:1220} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-11-16 01:27:03,057] {local_task_job.py:188} WARNING - State of this instance has been externally set to success. Terminating instance.
[2022-11-16 01:27:03,514] {process_utils.py:100} INFO - Sending Signals.SIGTERM to GPID 145
[2022-11-16 01:27:03,585] {process_utils.py:66} INFO - Process psutil.Process(pid=145, status='terminated', exitcode=0, started='01:26:42') (145) terminated with exit code 0
